<?php

/**
 * Implements hook_library_info_alter().
 */
function ckeditor5_demo_library_info_alter(&$libraries, $extension) {
  if ($extension == 'ckeditor5_demo') {
    $cdn_url = Drupal::config('ckeditor5_demo.settings')->get('cdn_url');
    if (!$cdn_url) {
      return;
    }
    $settings = [
      'type' => 'external',
      'minified' => TRUE,
    ];
    // Put ckeditor.js before init script, so it will be declared first.
    $libraries["ckeditor5"]["js"] = array_merge([$cdn_url => $settings], $libraries["ckeditor5"]["js"]);
  }
}
